version: 2.1


commands:
  setup:
    description: "Install the right node and check version"
    steps:
      - checkout
      # Install the right node version
      - run: source /home/circleci/.bashrc && nvm install 10.10.0
      - run: echo 'export PATH=/opt/circleci/.nvm/versions/node/v10.10.0/bin:$PATH' >> $BASH_ENV
      - run: node --version
      # Make sure that we are developing on a new version
      - run: npm show fuzzy-testing versions | grep -v "$(jq '.version' package.json | tr -d '"')"
      - run: npm install -g npm


jobs:
  test:
    machine: true
    steps:
      - setup
      - run: npm install

  publish:
    machine: true
    steps:
      - setup
      - run: npm install
      # Get the authentication token
      - run: echo `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` > .npmrc
      - run: npm publish


workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*?/
      - publish:
          filters:
            tags:
              only: /.*?/
            branches:
              ignore: /.*?/
